spring:
   profiles:
      active:

        - beta
---

server:
  port: 8888

mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
    


mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
      name: provider
  profiles: beta


logging:
  level:
    org.springframework.security: debug

eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka:7301/eureka
      #绕过登录页面
